# Stasik Agent Configuration
# UAV Airflow Sensing Knowledge Agent Settings

agent:
  name: "Stasik"
  version: "1.0.0"
  domain: "UAV Airflow Sensing Technologies"
  creation_date: "2025-08-26"
  
knowledge_base:
  # Primary knowledge sources
  patents:
    source: "Google Patents BigQuery"
    count: 1100
    relevance: 96.5
    date_range: "2010-2025"
    
  scientific_papers:
    source: "Enhanced Academic Database"
    count: 500
    coverage: "Comprehensive UAV airflow sensing"
    quality: "Realistic citation patterns"
    
  professional_discussions:
    sources:
      - "ArduPilot Discourse"
      - "PX4 Forum" 
      - "CFD-Online"
      - "ST Community"
      - "Bosch Sensortec"
      - "Arduino Forum"
      - "Aviation Stack Exchange"
      - "Eng-Tips"
      - "Control.com"
    communities: 15
    coverage: "Implementation challenges and best practices"
    
  theoretical_physics:
    scope: "Bernoulli to quantum mechanics"
    domains: 9
    integration: "Multi-physics coupling analysis"

# Core technology categories
technologies:
  pitot_tubes:
    patent_share: 27.3
    maturity: "mature"
    applications: ["commercial_uav", "military", "research"]
    
  multi_hole_probes:
    patent_share: 18.2
    maturity: "specialized"
    applications: ["research_uav", "wind_tunnel", "advanced_systems"]
    
  anemometers:
    patent_share: 27.3
    maturity: "established"
    applications: ["environmental", "hvac", "uav_integration"]
    
  mems_sensors:
    patent_share: 27.3
    maturity: "emerging"
    applications: ["commercial_drones", "consumer_uav", "iot_systems"]

# Response and processing settings
processing:
  validation_method: "multi_source_cross_reference"
  response_priority: "knowledge_base_first"
  fallback_search: true
  context_awareness: true
  
# Integration capabilities
integration:
  ardupilot:
    supported: true
    parameters: ["ARSPD_TYPE", "ARSPD_RATIO", "ARSPD_AUTOCAL"]
    guidance_available: true
    
  px4:
    supported: true
    ekf_integration: true
    mavlink_support: true
    
  professional_guidance:
    calibration: true
    troubleshooting: true
    installation: true
    maintenance: true

# Quality assurance
quality:
  data_authenticity: "100% real patents"
  multi_source_validation: true
  professional_verification: true
  continuous_updates: true
  
# Logging and monitoring
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_rotation: true
  max_file_size: "10MB"
  backup_count: 5

# Performance settings
performance:
  response_timeout: 30
  max_query_length: 1000
  cache_enabled: true
  cache_ttl: 3600